FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN chmod +x node_modules/.bin/*
RUN npm run build
RUN rm -rf *.md test/ tests/ __tests__/ src/dev-tools/
RUN npm install -g serve

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]