name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        script: |
          set -euo pipefail

          echo "Starting production deployment..."

          # Navigate to project directory
          cd /root/bestdeal_shipping

          echo "Syncing repo to remote production..."
          git fetch origin
          git checkout production
          git reset --hard origin/production
          git clean -fd

          echo "Writing env file from secrets..."
          printf "DB_PASSWORD=%s\nJWT_SECRET=%s\nJWT_REFRESH_SECRET=%s\nREACT_APP_API_URL=http://localhost:5000\nCORS_ORIGINS=%s\n" \
            "${{ secrets.DB_PASSWORD }}" \
            "${{ secrets.JWT_SECRET }}" \
            "${{ secrets.JWT_REFRESH_SECRET }}" \
            "${{ secrets.CORS_ORIGINS }}" > .env

          echo "Creating database backup..."
          docker exec bestdeal_postgres pg_dump -U bestdeal_user bestdeal_shipping > backup-$(date +%Y%m%d-%H%M%S).sql || true

          echo "Stopping and removing existing stack..."
          docker-compose -f docker-compose.prod.yml down --remove-orphans || true
          docker rm -f bestdeal_postgres bestdeal_backend bestdeal_frontend 2>/dev/null || true

          echo "Freeing space (optional)..."
          docker system prune -af || true

          echo "Rebuilding images with no cache and pulling latest bases..."
          docker-compose -f docker-compose.prod.yml build --no-cache --pull

          echo "Starting services..."
          docker-compose -f docker-compose.prod.yml up -d

          echo "Waiting for services to start..."
          sleep 30

          echo "Running database migrations..."
          docker-compose -f docker-compose.prod.yml exec -T backend npx prisma db push

          echo "Checking service health..."
          docker-compose -f docker-compose.prod.yml ps
          echo "Production deployment completed successfully!"