name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        script: |
          set -euo pipefail

          echo "Starting production deployment..."

          # Navigate to project directory
          cd /root/bestdeal_shipping

          echo "Syncing repo to remote production..."
          git fetch origin
          git checkout production
          git reset --hard origin/production
          git clean -fd

          echo "Writing env file from secrets..."
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
          echo "REACT_APP_API_URL=http://localhost:5000" >> .env
          echo "CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}" >> .env

          echo "Creating database backup..."
          docker exec bestdeal_postgres pg_dump -U bestdeal_user bestdeal_shipping > backup-$(date +%Y%m%d-%H%M%S).sql || true

          echo "Stopping and removing existing stack..."
          docker-compose -f docker-compose.prod.yml down --remove-orphans || true
          docker rm -f bestdeal_postgres bestdeal_backend bestdeal_frontend 2>/dev/null || true

          echo "Freeing space (optional)..."
          docker system prune -af || true

          echo "Rebuilding images with no cache and pulling latest bases..."
          docker-compose -f docker-compose.prod.yml build --no-cache --pull

          echo "Starting services..."
          docker-compose -f docker-compose.prod.yml up -d

          echo "Waiting for services to start..."
          sleep 30

          echo "Running database migrations..."
          docker-compose -f docker-compose.prod.yml exec -T backend npx prisma db push

          echo "Checking service health..."
          docker-compose -f docker-compose.prod.yml ps
          echo "Production deployment completed successfully!"