name: Deploy to Production

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        script: |
          echo "íº€ Starting production deployment..."
          
          # Navigate to project directory
          cd /root/bestdeal_shipping
          
          # Backup database
          docker exec bestdeal_postgres pg_dump -U bestdeal_user bestdeal_shipping > backup-$(date +%Y%m%d-%H%M%S).sql
          
          # Pull latest changes
          git pull origin production
          
          # Use production compose file
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d --build
          
          # Run migrations
          docker-compose -f docker-compose.prod.yml exec -T backend npx prisma db push
          
          echo "âœ… Production deployment completed!"
